"""Initial migration

Revision ID: fe14592dd79e
Revises: 
Create Date: 2025-02-28 17:21:38.852284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe14592dd79e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cover', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('cover')
        batch_op.drop_column('image')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
